create database poblacion;
use poblacion;
CREATE TABLE nombres (
  cod int auto_increment primary key,
  nombre varchar(250)
);

INSERT INTO nombres (nombre) VALUES
('ROBERTO SANTANA VIVANCOS'),
('EUGENIO SANCHIS SEGUI'),
('RAFAEL NAVA GIRALDEZ'),
('DANIEL VALDES CASTELLA'),
('JULIAN LUCENA PUERTO'),
('NICOLAS LORITE ROJO'),
('MARGARITA ABAD UTRERA'),
('MARTA ANAYA LLANO'),
('CLAUDIA SOBRINO AMOROS'),
('NATALIA BAEZA AGUILO'),
('SOFIA HIGUERAS ROCA'),
('ROSA MARIA BOLAÑOS SOLERA'),
('JOSEFA MATOS CADENAS'),
('MIGUEL ARRIZABALAGA ORGAZ'),
('TOMAS CAPARROS MENDIETA'),
('DIEGO LAMAS COCA'),
('SAMUEL VALDIVIESO MAQUEDA'),
('JUAN FRAILE BARRANCO'),
('IRENE ALFONSO BAÑON'),
('MIRIAM COMESAÑA SALVA');